name: LangGS
channels:
  - conda-forge
  - nvidia/label/cuda-11.8.0
dependencies:
  - python=3.10
  - cuda-toolkit
  - plyfile>=0.8.1
  - tqdm
  - pip
  - libstdcxx-ng>=13
  - libgcc-ng>=13
  - icu>=78

  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cu118
    - torch==2.0.1+cu118
    - torchvision==0.15.2+cu118
    - torchaudio==2.0.2+cu118
    - opencv-python>=4.8.1.78
    - munch
    - trimesh
    - timm
    - evo>=1.11.0
    - open3d
    - torchmetrics
    - imgviz
    - PyOpenGL
    - pytorch_lightning
    - pydantic>=1.10.18
    - glfw
    - fastapi>=0.88.0
    - submodules/simple-knn
    - submodules/diff-gaussian-rasterization
    - opencv-python==4.8.1.78
    - munch
    - trimesh
    - timm==1.0.9
    - evo==1.11.0
    - open3d==0.17.0
    - torchmetrics
    - imgviz
    - PyOpenGL
    - pytorch_lightning==1.9.0
    - pydantic==1.10.18
    - glfw
    - fastapi==0.88.0
    - PyGLM
    - wandb
    - lpips
    - rich
    - ruff
    - ftfy>=6.0.1
    - scipy
    - regex
    - einops
    - imageio>=2.4.1
    - ftfy==6.0.1
    - scipy==1.7.0
    - regex
    - einops
    - imageio==2.4.1
    - jaxtyping
